language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x mvnw

script: "./mvnw clean build -DskipTests"

notifications:
  email:
    recipients:
      - boxak@naver.com