language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x mvnw

script: "./mvnw clean install -DskipTests"

before_deploy:
  - zip -r springboot-webservice ./*
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-bucket-boxak
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true
    on:
      repo: boxak/dict
      branch: master
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-bucket-boxak
    key: springboot-webservice.zip
    bundle_type: zip
    application: springboot-webservice
    deployment_group: springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: boxak/dict
      branch: master

notifications:
  email:
    recipients:
      - boxak@naver.com